name: Test
on: [push, pull_request]
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rover fetch
        uses: ./
        with:
          args: subgraph fetch ${{ secrets.APOLLO_GRAPH_ID }}@current --name products
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rover publish
        uses: ./
        with:
          args: subgraph publish ${{ secrets.APOLLO_GRAPH_ID }}@current --name products --schema ./products.graphql
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}