name: Test
on: [push, pull_request]
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rover fetch
        uses: ./
        with:
          args: subgraph fetch rover-actions@current --name products
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  introspect:
    runs-on: ubuntu-latest
    services:
      apollo:
        image: danielsinclair/apollo-example
    steps:
      - uses: actions/checkout@v2
      - name: rover introspect
        uses: ./
        with:
          args: subgraph introspect http://apollo:3000/ > products.graphql
  push:
    needs: introspect
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rover publish
        uses: ./
        with:
          args: subgraph publish rover-actions@current --name products --schema ./products.graphql
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}