name: Test
on: [push, pull_request]
jobs:
  introspect:
    defaults:
      run:
        shell: bash
        working-directory: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t pm2 .
      - uses: addnab/docker-run-action@v3
        with:
          image: pm2
      - run: |
          sleep 5
          if curl http://localhost:3000/
          then echo "server reachable"
          else >&2 echo "server unreachable"
          fi
      - name: rover introspect
        uses: ./
        with:
          args: subgraph introspect http://localhost:3000/
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rover fetch
        uses: ./
        with:
          args: subgraph fetch rover-actions@current --name products
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rover publish
        uses: ./
        with:
          args: subgraph publish rover-actions@current --name products --schema ./test/products.graphql
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}